server:
  port: 8080

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://cloudmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: thirdparty_route
          uri: lb://cloudmall-thirdparty
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        - id: member_route
          uri: lb://cloudmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: ware_route
          uri: lb://cloudmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://cloudmall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /cloudmall-admin/$\{segment}


  application:
    name: cloudmall-gateway



