server:
  port: 9400

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/cloudmall_pms?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: cloudmall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.faxi.cloudmall.product: debug


feign:
  sentinel:
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

    #关闭thymeleaf缓存
  thymeleaf:
    cache: false


#线程池配置参数
cloudmall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10